---
- name: Restart apache
  ansible.builtin.systemd:
    name: "{{ apache_service }}"
    state: restarted
    daemon_reload: true
  listen: restart apache

- name: Reload apache
  ansible.builtin.systemd:
    name: "{{ apache_service }}"
    state: reloaded
  listen: reload apache

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  listen: reload firewalld
